name: On-demand self-hosted AWS EC2 runner for GitHub Actions
description: GitHub Action for automatic creation and registration AWS EC2 instance as a GitHub Actions self-hosted runner.
author: Volodymyr Machula
branding:
  icon: 'box'
  color: 'orange'
inputs:
  mode:
    description: >-
      Specify here which mode you want to use:
        - 'start' - to start a new runner;
        - 'stop' - to stop the previously created runner.
    required: true
  reuse-runner:
    description: >-
      Specify here if you want to reuse runner. EC2 runner instance
      will be hiberneted and resume if this is true.
    required: true
    default: 'true'
  github-token:
    description: >-
      GitHub Personal Access Token with the 'repo' scope assigned.
    required: true
  ec2-image-id:
    description: >-
      EC2 Image Id (AMI). The new runner will be launched from this image.
      This input is required if you use the 'start' mode.
    required: false
  ec2-instance-type:
    description: >-
      EC2 Instance Type. 
      This input is required if you use the 'start' mode.
    required: false
  subnet-id:
    description: >-
      VPC Subnet Id. The subnet should belong to the same VPC as the specified security group.
      This input is required if you use the 'start' mode.
    required: false
  security-group-id:
    description: >-
      EC2 Security Group Id. 
      The security group should belong to the same VPC as the specified subnet.
      The runner doesn't require any inbound traffic. However, outbound traffic should be allowed.
      This input is required if you use the 'start' mode.
    required: false
  ec2-instance-id:
    description: >-
      EC2 Instance Id of the created runner.
      The id is used to terminate the EC2 instance when the runner is not needed anymore.
      This input is required if you use the 'stop' mode.
    required: false
  iam-role-name:
    description: >-
      IAM Role Name to attach to the created EC2 instance.
      This requires additional permissions on the AWS role used to launch instances.
    required: false
  aws-resource-tags:
    description: >-
      Tags to attach to the launched EC2 instance and volume.
      This must be a stringified array of AWS Tag objects, with both Key and Value fields,
      for example: '{"TagKey1": "TagValue1", "TagKey2": "TagValue2"}'
    required: false
    default: '{}'
  runner-home-dir:
    description: >-
      Directory that contains actions-runner software and scripts. E.g. /home/runner/actions-runner.
    required: false
outputs:
  ec2-instance-id:
    description: >-
      EC2 Instance Id of the created runner.
      The id is used to terminate the EC2 instance when the runner is not needed anymore.
runs:
  using: node12
  main: ./dist/index.js
